language: python
before_install:
  sudo add-apt-repository -y ppa:cassou/emacs &&
  sudo apt-get update -qq &&
  sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot vim zsh python-setuptools;
  pip install dotfiles;
  ln -s $TRAVIS_BUILD_DIR /home/travis/configuration
install: zsh ./install.sh
script: echo "ok"
