language: nix

os:
  - linux
  # - osx

env:
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-27.1
  - EMACS_CI=emacs-snapshot

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

script:
  ./test_startup.sh
