# SCM part
branches:
  only:
    - master

# System part
matrix:
  include:
    - os: linux

language: python

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-elisp/ppa"
    packages:
      - emacs-snapshot
      - vim
      - zsh
      - python-setuptools

before_install:
  - pip install dotfiles
  - ln -s $TRAVIS_BUILD_DIR /home/travis/configuration

install: zsh ./install.sh
script: echo "ok"
