# SCM part
branches:
  only:
    - master

# System part
matrix:
  include:
    - dist: xenial

language: python

addons:
  apt:
    sources:
      - sourceline: "ppa:kelleyk/emacs"
    packages:
      - emacs26
      - vim
      - zsh
      - python-setuptools

before_install:
  - pip install dotfiles
  - ln -s $TRAVIS_BUILD_DIR /home/travis/configuration
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --set emacs /usr/bin/emacs26; fi

install:
  - zsh ./install.sh

script:
  - /usr/bin/emacs --version
  - emacs -Q --batch --eval "
    (progn
      (require 'ob-tangle)
      (dolist (file command-line-args-left)
        (with-current-buffer (find-file-noselect file)
          (org-babel-tangle))))" "~/.emacs.d/main.org"
  - /usr/bin/emacs --debug-init -nw -Q --batch -L ~/.emacs.d --eval "(require 'init)"
